### PR TITLE
Partial fix for #19

### LINKED ISSUE #19: Implement Redis 4.x missing req/res commands
Most should be highlighted by `FIXME` and/or `TODO` in code

### PR DESCRIPTION
**Pull request by sirocchj**
@barambani feel free to take a stab at reviewing it.

Here's a list of what's missing (may not be exhaustive):
- [ ] Scripting & Streams protocol
- [ ] Tests for PublishP, ServerP, SetP, SortedSetP, StringP and TransactionP
- [ ] Some FIXME and command combinations missing

### CODE REVIEW

File: core/src/main/scala/laserdisc/protocol/EitherSyntax.scala [hunk 1]
```diff
@@ -7,13 +7,13 @@ private[protocol] trait EitherSyntax {
 }
 
 final private[protocol] class EitherValuesSyntaxOps[A](private val a: A) extends AnyVal {
-  def asLeft[B]: A | B  = Left(a).widenAsRightOf[|, B]
-  def asRight[B]: B | A = Right(a).widenAsLeftOf[B, |]
+  def asLeft[B]: A | B  = Left(a)
```
Comment (barambani) [inline core/src/main/scala/laserdisc/protocol/EitherSyntax.scala]: 👍 , nice cleanup

**Comment by sirocchj** [comment]
That was easy lol
